--------------------------------------------------------
--  File created - Wednesday-December-21-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DOCTOR
--------------------------------------------------------

  CREATE TABLE "HOSPITAL"."DOCTOR" 
   (	"ID" NUMBER, 
	"FULL_NAME" VARCHAR2(45 BYTE), 
	"DOB" VARCHAR2(45 BYTE), 
	"QUALIFICATION" VARCHAR2(45 BYTE), 
	"SPECIALIST" VARCHAR2(45 BYTE), 
	"EMAIL" VARCHAR2(45 BYTE), 
	"MOBNO" VARCHAR2(45 BYTE), 
	"PASSWORD" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HOSPITAL.DOCTOR
SET DEFINE OFF;
Insert into HOSPITAL.DOCTOR (ID,FULL_NAME,DOB,QUALIFICATION,SPECIALIST,EMAIL,MOBNO,PASSWORD) values (1,'Dr.Debadutta Das','2022-12-22','mbbs','heart','debadattadas33@gmail.com','9090746993','1234');
Insert into HOSPITAL.DOCTOR (ID,FULL_NAME,DOB,QUALIFICATION,SPECIALIST,EMAIL,MOBNO,PASSWORD) values (2,'Dr.Mahesh','2021-02-21','mbbs','Dentist','doctor123@gmail.com','9090746993','1234');
Insert into HOSPITAL.DOCTOR (ID,FULL_NAME,DOB,QUALIFICATION,SPECIALIST,EMAIL,MOBNO,PASSWORD) values (3,'DR.Sasmita Das','2022-12-07','BBS','caridology','sasmita@gmail.com','9090746993','1234');
Insert into HOSPITAL.DOCTOR (ID,FULL_NAME,DOB,QUALIFICATION,SPECIALIST,EMAIL,MOBNO,PASSWORD) values (4,'Dr.Soumya Ranjan Das','2022-12-15','mbbs','dibetis','soumya12@gmail.com','94396364885','1234');
--------------------------------------------------------
--  DDL for Index DOCTOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSPITAL"."DOCTOR_PK" ON "HOSPITAL"."DOCTOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger DOCTOR_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSPITAL"."DOCTOR_TRG" 
BEFORE INSERT ON DOCTOR 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT DOCTOR_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSPITAL"."DOCTOR_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table DOCTOR
--------------------------------------------------------

  ALTER TABLE "HOSPITAL"."DOCTOR" ADD CONSTRAINT "DOCTOR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSPITAL"."DOCTOR" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "HOSPITAL"."DOCTOR" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "HOSPITAL"."DOCTOR" MODIFY ("SPECIALIST" NOT NULL ENABLE);
  ALTER TABLE "HOSPITAL"."DOCTOR" MODIFY ("QUALIFICATION" NOT NULL ENABLE);
  ALTER TABLE "HOSPITAL"."DOCTOR" MODIFY ("DOB" NOT NULL ENABLE);
  ALTER TABLE "HOSPITAL"."DOCTOR" MODIFY ("FULL_NAME" NOT NULL ENABLE);
  ALTER TABLE "HOSPITAL"."DOCTOR" MODIFY ("ID" NOT NULL ENABLE);
